import React from 'react';

const About = () => {
    return (
        <div className='container'>
            <div className='mt-2' style={{fontSize:'1.5vw', fontFamily: 'serif', textAlign: 'justify'}}>
                <h1 style={{textAlign: 'center'}}>Megami Tensei</h1> 
                Marketed internationally as Shin Megami Tensei (formerly Revelations), is a Japanese media franchise created by Kouji "Cozy" Okada, Ginichiro Suzuki, and Kazunari Suzuki. Primarily developed by Atlus and currently owned by Sega, the franchise consists of multiple subseries and covers multiple role-playing genres including tactical role-playing, action role-playing, and massively multiplayer online role-playing. The first two titles in the series were published by Bandai Namco (then Namco), but have been almost always published by Atlus in Japan and North America since the release of Shin Megami Tensei. For Europe, Atlus publishes the games through third-party companies.
                The series was originally based on Digital Devil Story, a science fiction novel series by Aya Nishitani. The series takes its name from the first book's subtitle. Most Megami Tensei titles are stand-alone entries with their own stories and characters. Recurring elements include plot themes, a story shaped by the player's choices, and the ability to fight using and often recruit creatures (demons, Personas) to aid the player in battle. Elements of philosophy, religion, occultism, cyberpunk, and science fiction have all been incorporated into the series at different times.
                <br/>
                <br/>
                <h1 style={{textAlign: 'center'}}>Persona</h1>
                Also known as Shin Megami Tensei: Persona, is a video game franchise developed and primarily published by Atlus. Focusing around a series of role-playing video games, Persona is a spin-off from Atlus' Megami Tensei franchise, and was originally based on the high school setting of Shin Megami Tensei If.... The first entry in the series, Revelations: Persona, was released in 1996. There have since been five further main games, with the most recent, Persona 5, being released in 2016. Numerous spin-offs have also been developed. The series takes its title from beings summoned by characters in battle, manifesting from their psychological persona.
                Persona began as a spin-off based on the positively-received setting of If.... Its trademark features include a high school setting, a group of students as the protagonists, a silent protagonist similar to the mainline Megami Tensei franchise, and combat using Personas. Since the release of Persona 3 in 2006, the main series has used a social simulation function called Social Links, which is directly linked to how Personas evolve. Central character designs are by series co-creator Kazuma Kaneko (Persona and the Persona 2 duology) and Shigenori Soejima (Persona 3 onwards). Its overall theme is exploration of the human psyche and how the characters find their true selves. The series' recurring concepts and design elements draw on Jungian psychology and archetypes, along with religion, mythology, and popular literature.
                Revelations: Persona was the first role-playing Megami Tensei title to be released outside of Japan. Beginning with Persona 2: Eternal Punishment, the English localizations began to remain faithful to the Japanese versions at the insistence of Atlus. The series is highly popular internationally, becoming the best-known Megami Tensei spin-off and establishing Atlus and the Megami Tensei franchise in North America. Following the release of Persona 3 and 4, the series also established a strong following in Europe. The series has since gone on to sell a total of over nine million copies worldwide, outselling its parent franchise. There have been numerous adaptations, including anime television and theatrical series, novelizations, mangas, stage plays, radio dramas, and musical concerts.
            </div>
        </div>
    );
};

export default About;